project:
  type: website

website:
  title: "Grace Winlett's Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Skills & Certifications"
        file: skills.qmd
      - text: "Contact"
        file: contact.qmd
      - text: "Volunteering"
        file: volunteer.qmd
  page-footer: 
    left: "© 2025 Grace WL"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - flatly 
    css: styles.css
    toc: false



